#!/bin/bash
set -eux

os-svc-install -n nova -u nova -r https://github.com/openstack/nova.git

mkdir -p /var/run/nova/keys && chown -R nova:nova /var/run/nova/keys
mkdir -p /var/log/nova && chown -R nova:nova /var/log/nova

install -d -m 0750 -o nova -g nova /etc/nova
cp -a /opt/stack/nova/etc/nova/rootwrap* /etc/nova

ln -sf /opt/stack/venvs/nova/bin/nova-rootwrap /usr/local/bin/nova-rootwrap

echo "nova ALL=(root) NOPASSWD: /opt/stack/venvs/bin/nova-rootwrap" > /etc/sudoers.d/nova
chmod 0440 /etc/sudoers.d/nova
visudo -c
