#!/bin/bash
set -eux

os-svc-install -n nova -u nova -r /opt/stack/nova

cp /opt/stack/nova/etc/nova/policy.json /etc/nova/policy.json
cp /opt/stack/nova/etc/nova/api-paste.ini /etc/nova/api-paste.ini
cp -a /opt/stack/nova/etc/nova/rootwrap* /etc/nova

ln -sf /opt/stack/venvs/nova/bin/nova-rootwrap /usr/local/bin/nova-rootwrap

echo "nova ALL=(root) NOPASSWD: /usr/local/bin/nova-rootwrap" > /etc/sudoers.d/nova
chmod 0440 /etc/sudoers.d/nova
visudo -c
