#!/bin/bash
set -eux

install-packages build-essential python-dev libssl-dev libxml2-dev libxslt-dev libffi-dev

# -s enables system-site-packages explicitly for python-libvirt
os-svc-install $NOVA_EXTRA_INSTALL_OPTS -i "$NOVA_VENV_DIR" -u nova -r /opt/stack/nova

cp /opt/stack/nova/etc/nova/policy.json /etc/nova/policy.json
cp /opt/stack/nova/etc/nova/api-paste.ini /etc/nova/api-paste.ini
cp -a /opt/stack/nova/etc/nova/rootwrap* /etc/nova
chown -R root.nova /etc/nova

ln -sf $NOVA_VENV_DIR/bin/nova-rootwrap /usr/local/bin/nova-rootwrap

echo "nova ALL=(root) NOPASSWD: /usr/local/bin/nova-rootwrap" > /etc/sudoers.d/nova
chmod 0440 /etc/sudoers.d/nova
visudo -c

add-selinux-path-substitution /usr/bin $NOVA_VENV_DIR/bin
