#!/bin/bash
# dib-lint: disable=sete

source $TRIPLEO_ROOT/tripleo-incubator/scripts/set-os-type
TE_BROKER_USER=ubuntu
if [ $TRIPLEO_OS_DISTRO = "fedora" ] ; then
    TRIPLEO_OS_DISTRO="fedora selinux-permissive"
    TE_BROKER_USER=fedora
fi

export TE_DISTRO=$TRIPLEO_OS_DISTRO
export TE_EXTRA_ELEMENTS=
export TE_PROVIDER_NET_NAME=datacentre
export TE_GEARMANHOST=172.16.3.254

export TE_OVERCLOUDPASSWD=$(awk '$1=="tripleo-ci" { print $2 }' < /os-asserted-users)
export TE_OVERCLOUDNPPASSWD=$(awk '$1=="openstack-nodepool" { print $2 }' < /os-asserted-users)
export TE_CPUPERENV=3
export TE_DISKPERENV=150
# It should 16 here but free -g is reporting 62 instead of 64G
export TE_MEMPERENV=15

export TE_BROKER_FLAVOR=m1.medium
