#!/bin/bash
# dib-lint: disable=sete

export TRIPLEO_ROOT="$(readlink -f $(dirname $0)/../../../..)"
source $(dirname ${BASH_SOURCE})/te_commonrc

export TE_OVERCLOUDIP=10.1.8.37
export TE_OVERCLOUDDNS=ci-overcloud.rh1.tripleo.org
export TE_EXTRA_ELEMENTS="stable-interface-names"
export TE_AUTHURL=http://$TE_OVERCLOUDIP:5000/v2.0
export TE_PUBLICINTERFACE=em1
export TE_COUNT=6
export TE_NP_RAM_QUOTA=180000
export TE_NTPSERVER=
