#!/bin/bash

export TRIPLEO_ROOT="$(readlink -f $(dirname $0)/../../../..)"
source $(dirname ${BASH_SOURCE})/te_commonrc

export TE_OVERCLOUDIP=10.1.8.37
export TE_OVERCLOUDDNS=ci-overcloud.rh1.tripleo.org
export TE_OVERCLOUDPASSWD=$(awk '$1=="tripleo-ci" { print $2 }' < /root/os-asserted-users)
export TE_EXTRA_ELEMENTS="stable-interface-names"
export TE_AUTHURL=http://$TE_OVERCLOUDIP:5000/v2.0
export TE_GEARMANHOST=192.168.1.1
export TE_PUBLICINTERFACE=em1
export TE_COUNT=6
