#!/bin/bash
set -eux

install-packages lvm2 libssl-dev tgt libffi-dev nfs-common
echo "qpid-python" | tee -a /opt/stack/cinder/requirements.txt
os-svc-install -i "$CINDER_VENV_DIR" -u cinder -r /opt/stack/cinder

cp -a /opt/stack/cinder/etc/cinder/rootwrap* /etc/cinder
cp /opt/stack/cinder/etc/cinder/api-paste.ini /etc/cinder/api-paste.ini
cp /opt/stack/cinder/etc/cinder/policy.json /etc/cinder/policy.json

ln -sf $CINDER_VENV_DIR/bin/cinder-rootwrap /usr/local/bin/cinder-rootwrap

echo "cinder ALL=(root) NOPASSWD: /usr/local/bin/cinder-rootwrap" > /etc/sudoers.d/cinder
chmod 0440 /etc/sudoers.d/cinder
visudo -c
