#!/bin/bash
set -eux

os-svc-daemon nova-baremetal-deploy-helper nova nova-baremetal-deploy-helper "--config-dir /etc/nova"

ln -s /opt/stack/venvs/nova/bin/nova-baremetal-manage /usr/local/bin/nova-baremetal-manage
