#!/bin/bash
set -eux

install-packages libvirt-dev
$CEILOMETER_VENV_DIR/bin/pip install libvirt-python

os-svc-daemon ceilometer-agent-compute ceilometer ceilometer-agent-compute --config-dir /etc/ceilometer
