#!/bin/bash
set -eu

# TODO: resize volume group in response to config changes.
# TODO: is there a safe way to shrink a volume group?
vol_group=cinder-volumes
vol_file=/mnt/state/var/lib/cinder/${vol_group}-backing-file
size=$(os-apply-config --key cinder.volume_size_mb --type int)M

if ! vgs $vol_group; then
  if ! [ -f $vol_file ] ; then
      truncate -s $size $vol_file
  fi
  dev=`sudo losetup -f --show $vol_file`
  if ! vgs $vol_group; then vgcreate $vol_group $dev; fi
fi
