#!/bin/bash
set -eux

install-packages lvm2 libssl-dev tgt
echo "qpid-python" | tee -a /opt/stack/cinder/requirements.txt
os-svc-install -n cinder -u cinder -r /opt/stack/cinder -c cinder-all

mkdir -p /etc/tgt/conf.d
install -d -o root -g cinder -m 0770 /var/lib/cinder/volumes
register-state-path /var/lib/cinder
echo 'include /etc/tgt/conf.d/cinder_tgt.conf' > /etc/tgt/targets.conf
echo 'include /mnt/state/var/lib/cinder/volumes/*' > /etc/tgt/conf.d/cinder_tgt.conf

cp -a /opt/stack/cinder/etc/cinder/rootwrap* /etc/cinder
cp /opt/stack/cinder/etc/cinder/api-paste.ini /etc/cinder/api-paste.ini
cp /opt/stack/cinder/etc/cinder/policy.json /etc/cinder/policy.json

ln -sf /opt/stack/venvs/cinder/bin/cinder-rootwrap /usr/local/bin/cinder-rootwrap

echo "cinder ALL=(root) NOPASSWD: /usr/local/bin/cinder-rootwrap" > /etc/sudoers.d/cinder
chmod 0440 /etc/sudoers.d/cinder
visudo -c
