#!/bin/bash

set -eux

mkdir -p /etc/tgt/conf.d
install -d -o root -g cinder -m 0770 /var/lib/cinder/volumes
install -d -o root -g cinder -m 0770 /var/lib/cinder/nfs
register-state-path /var/lib/cinder
echo 'include /mnt/state/var/lib/cinder/volumes/*' > /etc/tgt/conf.d/cinder.conf
