#!/bin/bash
set -eu

os-svc-enable -n swift-account
os-svc-enable -n swift-container
os-svc-enable -n swift-object

os-svc-restart -n swift-account
os-svc-restart -n swift-container
os-svc-restart -n swift-object
