#!/bin/bash
set -eu

os-svc-enable -n swift-account
os-svc-enable -n swift-account-auditor
os-svc-enable -n swift-account-reaper
os-svc-enable -n swift-account-replicator
os-svc-enable -n swift-container
os-svc-enable -n swift-container-auditor
os-svc-enable -n swift-container-replicator
os-svc-enable -n swift-container-updater
os-svc-enable -n swift-object
os-svc-enable -n swift-object-auditor
os-svc-enable -n swift-object-replicator
os-svc-enable -n swift-object-updater
os-svc-enable -n rsync

os-svc-restart -n swift-account
os-svc-restart -n swift-account-auditor
os-svc-restart -n swift-account-reaper
os-svc-restart -n swift-account-replicator
os-svc-restart -n swift-container
os-svc-restart -n swift-container-auditor
os-svc-restart -n swift-container-replicator
os-svc-restart -n swift-container-updater
os-svc-restart -n swift-object
os-svc-restart -n swift-object-auditor
os-svc-restart -n swift-object-replicator
os-svc-restart -n swift-object-updater
os-svc-restart -n rsync
