#!/bin/bash
set -eux

os-svc-install $CEILOMETER_EXTRA_INSTALL_OPTS -i "$CEILOMETER_VENV_DIR" -u ceilometer -r /opt/stack/ceilometer


install -m 640 -o ceilometer -g ceilometer /opt/stack/ceilometer/etc/ceilometer/pipeline.yaml /etc/ceilometer
install -m 640 -o ceilometer -g ceilometer /opt/stack/ceilometer/etc/ceilometer/api_paste.ini /etc/ceilometer
install -m 640 -o ceilometer -g ceilometer /opt/stack/ceilometer/etc/ceilometer/policy.json /etc/ceilometer

# NOTE(gfidente): the following is needed by v1 api only, removed after icehouse release
# with ceilometer commit: 6a7d6ec198451687ad4389787338988012e6a1fe
if [ -f /opt/stack/ceilometer/etc/ceilometer/sources.json ]; then
    install -m 640 -o ceilometer -g ceilometer /opt/stack/ceilometer/etc/ceilometer/sources.json /etc/ceilometer
fi

ln -s $CEILOMETER_VENV_DIR/bin/ceilometer-dbsync /usr/local/bin/ceilometer-dbsync

add-selinux-path-substitution /usr/bin $CEILOMETER_VENV_DIR/bin
