#!/bin/bash
set -eux
install -m 0755 -o root -g root -t /usr/local/bin $(dirname $0)/../neutron-ovs-agent-bin/*
os-svc-daemon neutron-openvswitch-agent neutron neutron-openvswitch-agent \
    "--config-file /etc/neutron/neutron.conf  --config-file /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini --config-dir /etc/neutron"
