#!/bin/bash
# Install the image creation toolchain so folk can create their own images
# (also includes the bootstrap-from-devstack facilities needed until we have
# full image mastering of openstack).

set -eu
set -o xtrace

install-packages git
if [ -n "$http_proxy" ]; then
    sudo -Hiu stack git config --global http.proxy $http_proxy
fi

chown -R stack ~stack/incubator
