#!/bin/bash
# Initialize devstack in the bootstrap image

set -eu
set -o xtrace

install-packages git
if [ -n "$http_proxy" ]; then
    sudo -Hiu stack git config --global http.proxy $http_proxy
fi

chown -R stack ~stack/devstack
