#!/bin/bash
set -eu

install-packages mysql-server python-mysqldb

my_cnf=
if [ -f /etc/mysql/my.cnf ]; then
    my_cnf=/etc/mysql/my.cnf # Ubuntu
elif [ -f /etc/my.cnf ]; then
    my_cnf=/etc/my.cnf # Fedora/RHEL
fi

sed -i 's/127.0.0.1/0.0.0.0/g' $my_cnf

os-svc-install -u keystone -r /opt/stack/keystone
os-svc-install -u cinder   -r /opt/stack/cinder
os-svc-install -u nova     -r /opt/stack/nova
os-svc-install -u glance   -r /opt/stack/glance
os-svc-install -u neutron  -r /opt/stack/neutron
