#!/bin/bash
set -eu

install-packages mysql-server python-mysqldb

my_cnf=
if [ -f /etc/mysql/my.cnf ]; then
  my_cnf=/etc/mysql/my.cnf # Ubuntu
elif [ -f /etc/my.cnf ]; then
  my_cnf=/etc/my.cnf # Fedora/RHEL
fi

sed -i 's/127.0.0.1/0.0.0.0/g' $my_cnf

os-svc-install -u keystone -r https://github.com/openstack/keystone.git
os-svc-install -u cinder   -r https://github.com/openstack/cinder.git
os-svc-install -u nova     -r https://github.com/openstack/nova.git
os-svc-install -u glance   -r https://github.com/openstack/glance.git
os-svc-install -u quantum  -r https://github.com/openstack/quantum.git
