#!/bin/bash

set -e
set -o xtrace

export DELOREAN_REPO_FILE=${DELOREAN_REPO_FILE:-"delorean.repo"}

# delorean requires delorean-deps
if [[ "rhel7 centos7" =~ "$DISTRO_NAME" ]]; then

  if [ -z "$STABLE_RELEASE" ]; then
    curl -L http://trunk.rdoproject.org/centos7/delorean-deps.repo -o /etc/yum.repos.d/delorean-deps.repo
  else
    curl -L http://trunk.rdoproject.org/centos7-$STABLE_RELEASE/delorean-deps.repo -o /etc/yum.repos.d/delorean-deps.repo
  fi

elif [[ "fedora" =~ "$DISTRO_NAME" ]]; then
  curl -L http://trunk.rdoproject.org/f$DIB_RELEASE/delorean-deps.repo -o /etc/yum.repos.d/delorean-deps.repo
fi

if [ -n "$DELOREAN_REPO_URL" ]; then
  curl -L $DELOREAN_REPO_URL/$DELOREAN_REPO_FILE -o /etc/yum.repos.d/$DELOREAN_REPO_FILE
else
  echo "Please configure a DELOREAN_REPO_URL."
  exit 1
fi
