#!/bin/bash

set -eux

install-packages openstack-neutron-openvswitch

# Use the tripleo ml2 config, openvswitch-agent as installed by package starts with
# --config-file /etc/neutron/plugins/ml2/openvswitch_agent.ini
# --config-file /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini (pre liberty)
ML2CONFIG=/etc/neutron/plugins/ml2/openvswitch_agent.ini
if [ -e /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini ] ; then
    ML2CONFIG=/etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini
fi
rm -f $ML2CONFIG
ln -s /etc/neutron/plugins/ml2/ml2_conf.ini $ML2CONFIG

os-svc-daemon -n neutron-openvswitch-agent -u neutron
