#!/bin/bash
set -eux

install-packages libapache2-mod-wsgi libssl-dev libffi-dev

if [ -d /etc/apache2 ]; then
    ln -s /etc/httpd/conf.d/horizon.conf /etc/apache2/sites-available/horizon.conf
    ln -s /etc/httpd/conf.d/horizon.conf /etc/apache2/sites-enabled/horizon.conf
    ln -s /var/log/apache2 /var/log/httpd
    rm -f /etc/apache2/sites-enabled/{000-default.conf,default.conf,default-ssl.conf}
fi

os-svc-install -n horizon -u horizon -r /opt/stack/horizon

# Django won't start otherwise:
touch /etc/horizon/.secret_key_store
chmod 600 /etc/horizon/.secret_key_store
chown horizon:horizon /etc/horizon/.secret_key_store
