#!/bin/bash

set -eux
set -o pipefail

# https://bugs.centos.org/view.php?id=17133
rm -f /etc/sysconfig/network-scripts/ifcfg-ens*
# https://bugs.launchpad.net/tripleo/+bug/1931495
rm -f /etc/sysconfig/network-scripts/ifcfg-eth*
