#!/bin/bash

set -eux
set -o pipefail

# https://bugs.centos.org/view.php?id=17133
if ls /etc/sysconfig/network-scripts/ifcfg-ens3* &> /dev/null; then
    rm -f /etc/sysconfig/network-scripts/ifcfg-ens3*
fi
if ls /etc/sysconfig/network-scripts/ifcfg-eth* &> /dev/null; then
    rm -f /etc/sysconfig/network-scripts/ifcfg-eth*
fi
