#!/bin/bash
set -eu
set -o pipefail

set +u
source $HORIZON_VENV_DIR/bin/activate
set -u

pip install -r /opt/stack/tuskar-ui/requirements.txt
pip install -e /opt/stack/tuskar-ui

set +u
deactivate
set -u

cp /opt/stack/tuskar-ui/_50_tuskar.py.example $HORIZON_VENV_DIR/lib/python2.7/site-packages/openstack_dashboard/local/enabled/_50_tuskar.py
cp /opt/stack/tuskar-ui/_10_admin.py.example $HORIZON_VENV_DIR/lib/python2.7/site-packages/openstack_dashboard/local/enabled/_10_admin.py
cp /opt/stack/tuskar-ui/_20_project.py.example $HORIZON_VENV_DIR/lib/python2.7/site-packages/openstack_dashboard/local/enabled/_20_project.py
cp /opt/stack/tuskar-ui/_30_identity.py.example $HORIZON_VENV_DIR/lib/python2.7/site-packages/openstack_dashboard/local/enabled/_30_identity.py
