#!/bin/bash
# Copyright 2014 Hewlett-Packard Development Company, L.P.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eux
set -o pipefail

install-packages stunnel4

# Debian/Ubuntu don't install stunnel4 in a working configuration.
if [ -e /etc/default/stunnel4 ]; then
    cat > /etc/default/stunnel4 << EOF
ENABLED=1
FILES="/etc/stunnel/*.conf"
OPTIONS=""
PPP_RESTART=0
EOF
fi

FILES=$(dirname $0)/../files
FILE=/usr/lib/systemd/system/stunnel4.service
if [ "$(dib-init-system)" == "systemd" ]; then
    install -D -g root -o root -m 0755 "${FILES}${FILE}" "${FILE}"
fi

