#!/bin/bash
set -eu

add-rule INPUT -p tcp --dport 9696  -j ACCEPT

# DHCP, TFTP
add-rule INPUT -m udp -p udp --dport 69 -j ACCEPT

# Need to allow gre where used (on overcloud)
if [ "$(os-apply-config --key neutron.ovs.tenant_network_type)" = 'gre' ] ; then
    add-rule INPUT -p gre -j ACCEPT
fi


