#!/bin/bash
set -eux

install-packages openvswitch-switch openvswitch-datapath-dkms
os-svc-install -n quantum -u quantum -r https://github.com/openstack/quantum.git

mkdir -p /var/lib/quantum && chown -R quantum:quantum /var/lib/quantum

echo "quantum ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/quantum
chmod 0440 /etc/sudoers.d/quantum
visudo -c
