#!/bin/bash
set -e

install-packages python-mysqldb

cp -r /opt/stack/heat/etc/heat/environment.d /etc/heat
cp -r /opt/stack/heat/etc/heat/templates /etc/heat

os-svc-daemon heat-engine heat heat-engine
