#!/bin/bash
set -ex

# create softlink to /dev/null which disables the net-name-slot rules
# which rename eth0 -> em1, etc. We don't want to do this on the
# seed VM
if [ -d /etc/udev/rules.d/ ]; then
    ln -sf /dev/null /etc/udev/rules.d/80-net-name-slot.rules
fi

if [ -d /etc/sysconfig/network-scripts ]; then

    # enable DHCP on eth0 for the seed
    cat > /etc/sysconfig/network-scripts/ifcfg-eth0 <<EOF_CAT
DEVICE="eth0"
BOOTPROTO="dhcp"
ONBOOT="yes"
TYPE="Ethernet"
EOF_CAT

fi
