#!/bin/bash

set -uex

install-packages \
    python-pip python-psutil

mkdir -p /opt/stack
git clone --depth=1 https://github.com/openstack/heat-cfntools.git /opt/stack/heat-cfntools


# A new boto is needed for this bug fix: http://pad.lv/1177576 .
sed -i 's/^boto==2\.5\.2$/boto>=2.9.2/' /opt/stack/heat-cfntools/tools/pip-requires

pip install -r /opt/stack/heat-cfntools/tools/pip-requires

pushd /opt/stack/heat-cfntools
python setup.py install
popd

cfn-create-aws-symlinks --source /usr/local/bin
