#!/bin/bash

set -uex

install-packages \
    python-pip python-psutil python-virtualenv

mkdir -p /opt/stack/venvs

VENV=/opt/stack/venvs/heat-cfntools
virtualenv $VENV --system-site-packages

$VENV/bin/pip install heat-cfntools

# symlink to /opt/aws/bin
$VENV/bin/cfn-create-aws-symlinks --source $VENV/bin

# also symlink to /usr/local/bin
$VENV/bin/cfn-create-aws-symlinks --source $VENV/bin --target /usr/local/bin
