#!/bin/bash
set -eu

/opt/stack/venvs/cinder/bin/cinder-manage db sync

os-svc-enable -n cinder-api
os-svc-enable -n cinder-volume
os-svc-enable -n cinder-scheduler

service cinder-api restart
service cinder-volume restart
service cinder-scheduler restart
