#!/bin/bash
set -eux

install-packages python-mysqldb

os-svc-install -n glance -u glance -r /opt/stack/glance

mkdir -p /var/lib/glance/images && chown -R glance:glance /var/lib/glance/images
os-svc-daemon glance-api glance glance-api "--debug --log-config /etc/glance/logging.conf"
os-svc-daemon glance-reg glance glance-registry "--debug --log-config /etc/glance/logging.conf"

install -m 0755 -o glance -g glance -d /var/log/glance
