#!/bin/bash
set -eux

install-packages python-mysqldb libssl-dev

os-svc-install -n glance -u glance -r /opt/stack/glance

cp /opt/stack/glance/etc/policy.json /etc/glance/policy.json
cp /opt/stack/glance/etc/schema-image.json /etc/glance/schema-image.json
cp /opt/stack/glance/etc/glance-api-paste.ini /etc/glance/glance-api-paste.ini
cp /opt/stack/glance/etc/glance-registry-paste.ini /etc/glance/glance-registry-paste.ini

mkdir -p /var/lib/glance/images && chown -R glance:glance /var/lib/glance/images
os-svc-daemon glance-api glance glance-api
os-svc-daemon glance-reg glance glance-registry

install -m 0755 -o glance -g glance -d /var/log/glance
