#!/bin/bash
set -eux

# need the libssl header files
install-packages libssl-dev

os-svc-install $IRONIC_EXTRA_INSTALL_OPTS -i "$IRONIC_VENV_DIR" -u ironic -r /opt/stack/ironic

install -d -m 0750 -o ironic -g ironic /etc/ironic
install -o root -g root -m 0644 /opt/stack/ironic/etc/ironic/policy.json /etc/ironic

# Setup Ironic's rootwrap.
install -o root -g root -m 0755 -d /etc/ironic/rootwrap.d
install -o root -g root -m 0644 -t /etc/ironic/rootwrap.d /opt/stack/ironic/etc/ironic/rootwrap.d/*
install -o root -g root -m 0644 /opt/stack/ironic/etc/ironic/rootwrap.conf /etc/ironic/rootwrap.conf

ln -s $IRONIC_VENV_DIR/bin/ironic-dbsync /usr/local/bin/ironic-dbsync

ln -sf $IRONIC_VENV_DIR/bin/ironic-rootwrap /usr/local/bin/ironic-rootwrap

