#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eux
set -o pipefail

backup="/var/lib/use-ephemeral"
paths="${backup}/stateful-paths"
state="/mnt/state"

[ -e "${paths}" ] || exit 0

while read -r line; do
    path="${line%;*}"

    if [ -e "${path}" ]; then
        backup_dir="${backup}$(dirname "${path}")"
        mkdir -p "${backup_dir}"
        mv "${path}" "${backup_dir}"
    fi

    if [ -n "${line##*;}" ]; then
        ln -s "${state}${path}" "${path}"
    fi
done < "${paths}"

