#!/bin/bash
set -eux
set -o pipefail

os-svc-enable -an ceilometer-api

[ -d /mnt/state/var/lib/ceilometer ] || install -d -D -m 0770 -o ceilometer -g ceilometer /mnt/state/var/lib/ceilometer
[ -d /mnt/state/var/lib/ceilometer/keystone-signing ] || install -d -D -m 0770 -o ceilometer -g ceilometer /mnt/state/var/lib/ceilometer/keystone-signing

os-svc-restart -an ceilometer-api
