#!/bin/bash
set -eux

install-packages python-mysqldb libssl-dev

os-svc-install -u glance -r /opt/stack/glance

ln -s $GLANCE_VENV_DIR/bin/glance-manage /usr/local/bin/glance-manage

cp /opt/stack/glance/etc/policy.json /etc/glance/policy.json
cp /opt/stack/glance/etc/schema-image.json /etc/glance/schema-image.json
cp /opt/stack/glance/etc/glance-api-paste.ini /etc/glance/glance-api-paste.ini
cp /opt/stack/glance/etc/glance-registry-paste.ini /etc/glance/glance-registry-paste.ini

os-svc-daemon glance-api glance glance-api
os-svc-daemon glance-reg glance glance-registry
