#!/bin/bash
set -eux

os-svc-install $TUSKAR_EXTRA_INSTALL_OPTS  -i "$TUSKAR_VENV_DIR" -u tuskar -r /opt/stack/tuskar

install -d -m 0750 -o tuskar -g tuskar /etc/tuskar
cp -a /opt/stack/tuskar/etc/tuskar/policy.json /etc/tuskar

os-svc-daemon -i "$TUSKAR_VENV_DIR" tuskar-api tuskar tuskar-api "--config-dir /etc/tuskar"

ln -s $TUSKAR_VENV_DIR/bin/tuskar-dbsync /usr/local/bin/tuskar-dbsync
ln -s $TUSKAR_VENV_DIR/bin/tuskar-load-roles /usr/local/bin/tuskar-load-roles
