#!/bin/bash
# This script should remain idempotent as it may be called several times
set -eux

PATH=/usr/local/bin:$PATH

OVS_PHYSICAL_BRIDGE=$(os-config-applier --key quantum.ovs.physical_bridge --type raw --key-default '')
PUBLIC_INTERFACE=$(os-config-applier --key quantum.ovs.public_interface --type raw  --key-default '')

ovs-vsctl --no-wait -- --may-exist add-br br-int
ovs-vsctl --no-wait br-set-external-id br-int bridge-id br-int

if [ -n "$OVS_PHYSICAL_BRIDGE" ] && [ -n "$PUBLIC_INTERFACE" ]; then
    ovs-vsctl --no-wait -- --may-exist add-br $OVS_PHYSICAL_BRIDGE
    ovs-vsctl add-port $OVS_PHYSICAL_BRIDGE $PUBLIC_INTERFACE || echo "port already added?"
fi

if [ -n "$OVS_PHYSICAL_BRIDGE" ] && [ -n "$PUBLIC_INTERFACE" ] ; then
    # Right now we probably are disconnected, need to move all IPs from public interface to bridge
    for IP in $(ip addr show dev $PUBLIC_INTERFACE | grep ' inet ' | awk '{print $2}'); do
      ip addr del $IP dev $PUBLIC_INTERFACE

      if ! ip addr show $OVS_PHYSICAL_BRIDGE | grep $IP; then
        ip addr add $IP dev $OVS_PHYSICAL_BRIDGE
      fi
    done
    ifconfig $OVS_PHYSICAL_BRIDGE up
fi

service openvswitch-switch restart || service openvswitch restart
