#!/bin/bash
set -eu

PATH=/usr/local/bin:$PATH

OK_FILE=/opt/stack/boot-stack.ok
WIPING_FILE=/opt/stack/boot-stack.wiping

if [ -e $OK_FILE -o -e $WIPING_FILE ] ; then
    exit 0
fi

touch $WIPING_FILE

wipe-openstack

rm $WIPING_FILE

touch $OK_FILE

