#!/bin/bash
set -eux

mkdir -p /opt/stack/venvs
virtualenv /opt/stack/venvs/gear

/opt/stack/venvs/gear/bin/pip install gear

useradd gear
os-svc-daemon -an geard -u gear -c geard -- -d
os-svc-enable -an geard
