#!/bin/bash
set -eux
set -o pipefail

if [[ -x /usr/sbin/semanage ]]; then
    # Allow keepalived to load kernel modules
    # https://bugs.launchpad.net/tripleo/+bug/1342872
    setsebool -P domain_kernel_load_modules 1

    semanage fcontext -a -t var_log_t "/mnt/state/var/log/keepalived(/.*)?"
    restorecon -Rv /mnt/state/var/log/keepalived
fi
