#!/bin/bash
set -eux
set -o pipefail

# Allow keepalived to load kernel modules
# https://bugs.launchpad.net/tripleo/+bug/1342872
if [[ -x /usr/sbin/semanage ]]; then
    setsebool -P domain_kernel_load_modules 1
fi
