#!/bin/bash
set -eux
set -o pipefail

INTERFACES=$(os-apply-config --key virtual_interfaces.instances --type raw --key-default '')
if [ -z "$INTERFACES" ] ; then
    echo "No virtual interfaces to use"
    exit 1
fi

os-svc-enable -an keepalived

if [ -e /var/run/keepalived.pid ] && pgrep -F /var/run/keepalived.pid keepalived &>/dev/null; then
    service keepalived reload
else
    service keepalived restart
fi
