#!/bin/bash
set -eux

function install_dnsmasq_upstart {
  cat > /etc/init/nova-bm-dnsmasq.conf << eof
start on runlevel [2345]
stop on runlevel [016]
pre-start script
  mkdir -p /tftpboot
  chown -R nova:nova /tftpboot
  killall -9 dnsmasq || echo 'no dnsmasq running'
end script
task

script
  exec dnsmasq --conf-file= \\
               --port=0 \\
               --enable-tftp \\
               --tftp-root=/tftpboot \\
               --dhcp-boot=pxelinux.0 \\
               --bind-interfaces \\
               --pid-file=/var/run/dnsmasq.pid \\
               --interface=br-ctlplane \\
               --dhcp-range=192.0.2.65,192.0.2.69,29
end script
eof
}

function install_dnsmasq_systemd {
  cat > /etc/systemd/system/nova-bm-dnsmasq.conf << eof
[Unit]
Description=Nova dnsmasq service

[Service]
Type=forking
ExecStartPre=mkdir -p /tftpboot
ExecStartPre=chown -R nova:nova /tftpboot
ExecStartPre=killall -9 dnsmasq || echo 'no dnsmasq running'
ExecStart=dnsmasq --conf-file= \\
                  --port=0 \\
                  --enable-tftp \\
                  --tftp-root=/tftpboot \\
                  --dhcp-boot=pxelinux.0 \\
                  --bind-interfaces \\
                  --pid-file=/var/run/dnsmasq.pid \\
                  --interface=br-ctlplane \\
                  --dhcp-range=192.0.2.65,192.0.2.69,29

[Install]
WantedBy=multi-user.target
Alias=nova-bm-dnsmasq.service
eof
}

# Used by all compute
install-packages dnsmasq novnc dnsmasq-utils ebtables

# for libvirt clouds only
install-packages libvirt-bin python-libvirt kvm pm-utils syslinux

# Fedora don't always have the libvirtd group created
if ! grep ^libvirtd /etc/group > /dev/null 2>&1; then
  groupadd -f libvirtd
fi

usermod -a -G libvirtd nova

if [ -d /etc/init ]; then
  install_dnsmasq_upstart
elif [ -d /etc/systemd/system ]; then
  install_dnsmasq_systemd
fi

mkdir -p /tftpboot/pxelinux.cfg/
if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
  cp /usr/lib/syslinux/pxelinux.0 /tftpboot/ # Ubuntu
elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
  cp /usr/share/syslinux/pxelinux.0 /tftpboot/ # Fedora/RHEL
fi

os-svc-daemon nova-compute  nova nova-compute          "--config-dir /etc/nova"
os-svc-daemon nova-baremetal-deploy-helper nova nova-baremetal-deploy-helper "--config-dir /etc/nova"

chown -R nova:nova /var/lib/misc/

echo "nova ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/nova
chmod 0440 /etc/sudoers.d/nova
visudo -c

# Use the rootwrap config from the source repo.
install -o root -g root -m 0755 -d /etc/nova/rootwrap.d
for f in $(ls /opt/stack/nova/etc/nova/rootwrap.d/); do
  install -o root -g root -m 644 /opt/stack/nova/etc/nova/rootwrap.d/$f /etc/nova/rootwrap.d/$f
done
install -o root -g root -m 0644 /opt/stack/nova/etc/nova/rootwrap.conf /etc/nova/rootwrap.conf
