#!/bin/bash
set -eux

# for BUG: https://bugs.launchpad.net/neutron/+bug/1225232
echo "qpid-python" | tee -a /opt/stack/neutron/requirements.txt

os-svc-install $NEUTRON_EXTRA_INSTALL_OPTS -i "$NEUTRON_VENV_DIR" -u neutron -r /opt/stack/neutron

ln -sf $NEUTRON_VENV_DIR/bin/neutron-rootwrap /usr/bin/neutron-rootwrap
ln -sft /etc/neutron $NEUTRON_VENV_DIR/etc/neutron/rootwrap.d

cp /opt/stack/neutron/etc/api-paste.ini /etc/neutron/api-paste.ini
cp /opt/stack/neutron/etc/policy.json /etc/neutron/policy.json

ln -s $NEUTRON_VENV_DIR/bin/neutron-db-manage /usr/local/bin/neutron-db-manage

echo "neutron ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/neutron
echo "Defaults:neutron !requiretty" >> /etc/sudoers.d/neutron
chmod 0440 /etc/sudoers.d/neutron
visudo -c

add-selinux-path-substitution /usr/bin $NEUTRON_VENV_DIR/bin
