#!/bin/bash
set -eu


# This key is to be retrieved to allow nova to ssh
# into the host machine when using VirtualPowerManager
KEYPATH=/opt/stack/boot-stack/virtual-power-key
if [ ! -e $KEYPATH ] ; then
    ssh-keygen -t rsa -f $KEYPATH \
        -N '' -C 'boot-stack key for use with nova VirtualPowerDriver'
fi
chown nova:nova /opt/stack/boot-stack/virtual-power-key*
chmod 400 /opt/stack/boot-stack/virtual-power-key*

PATH=/usr/local/bin:$PATH

os-apply-config

wipe-openstack

touch /opt/stack/boot-stack.ok

