#!/bin/bash
set -eux

install-packages -m snmpd nagios_plugins_package snmpd_package snmp-mibs-downloader_package lm-sensors_package

# install our snmp check script
DEST_DIR="/usr/lib64/nagios/plugins"
if [ ! 'amd64' = "$ARCH" ] || [ ! -d $DEST_DIR ]; then
    DEST_DIR="/usr/lib/nagios/plugins"
fi
install -m 0755 -o root -g root $(dirname $0)/../files/check_proc_open_files.py $DEST_DIR/check_proc_open_files.py
install -m 0440 -o root -g root $(dirname $0)/../files/snmp /etc/sudoers.d/snmp
