#!/bin/bash
set -eux

os-svc-enable -n pacemaker

os-svc-restart -n pacemaker

# Give pacemaker some time to boot up, otherwise configuration commands
# time out. The issue is tracked here:
# https://bugzilla.redhat.com/show_bug.cgi?id=1111747
# This workaround can be removed once the issue above is fixed.
sleep 30
