#!/bin/bash
set -ex

manifest=$(get-pip-manifest os-net-config)

virtualenv --setuptools $OS_NET_CONFIG_VENV_DIR
set +u
source $OS_NET_CONFIG_VENV_DIR/bin/activate
set -u

if [ -n "$manifest" ]; then
    use-pip-manifest $manifest
else
    # bug #1201253 : virtualenv-1.10.1 embeds setuptools-0.9.8, which
    # doesn't manage correctly HTTPS sockets when downloading pbr from
    # https://pypi.python.org/simple/ if using http_proxy and https_proxy
    # envvars
    $OS_NET_CONFIG_VENV_DIR/bin/pip install -U 'setuptools>=1.0'
    # bug #1293812 : Avoid easy_install triggering on pbr.
    $OS_NET_CONFIG_VENV_DIR/bin/pip install -U 'pbr>=0.11,<2.0'
    $OS_NET_CONFIG_VENV_DIR/bin/pip install -U os-net-config
fi

# Write the manifest of what was installed
write-pip-manifest os-net-config

ln -s $OS_NET_CONFIG_VENV_DIR/bin/os-net-config /usr/local/bin/os-net-config

set +u
deactivate
set -u
