#!/bin/bash
set -eu
install-packages python-setuptools python-eventlet python-greenlet \
    python-httplib2 python-iso8601 python-lxml python-sqlalchemy \
    python-paste python-routes python-webob python-yaml libffi-dev

os-svc-install $HEAT_EXTRA_INSTALL_OPTS -i "$HEAT_VENV_DIR" -u heat -r /opt/stack/heat

cp /opt/stack/heat/etc/heat/policy.json /etc/heat/policy.json

install -d -m 0770 -o root -g heat /var/log/heat

add-selinux-path-substitution /usr/bin $HEAT_VENV_DIR/bin
