#!/bin/bash
set -eux

modprobe nbd || true

chown -R nova:nova /var/log/nova

mkdir -p /var/run/nova/instances
chown -R nova:nova /var/run/nova
mkdir -p /tftpboot
chown -R nova:nova /tftpboot

service nova-compute restart

compute_driver=$(os-config-applier --type raw --key nova.compute_driver)
if [ "$compute_driver" = "baremetal.driver.BareMetalDriver" ] ; then
    service nova-baremetal-deploy-helper restart
    service nova-bm-dnsmasq restart
else
    service nova-bm-dnsmasq stop || :
    service nova-baremetal-deploy-helper stop || :
fi
