#!/bin/bash

set -eux

install-packages openstack-neutron openstack-neutron-ml2

ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

os-svc-daemon -n neutron-server -u neutron -c noop -d

# Packaged neutron is providing a requires.txt which breaks dependencies at
# runtime. See:
# https://bugzilla.redhat.com/show_bug.cgi?id=1057615
rm -f /usr/lib/python2.7/site-packages/neutron-*.egg-info/requires.txt
