#!/bin/bash
set -eux

# for libvirt clouds only
install-packages libvirt-bin python-libvirt kvm pm-utils

# Fedora don't always have the libvirtd group created
if ! grep ^libvirtd /etc/group > /dev/null 2>&1; then
  groupadd -f libvirtd
fi

usermod -a -G libvirtd nova

os-svc-daemon nova-novncproxy  nova nova-novncproxy          "--config-dir /etc/nova"
