#!/bin/bash
os-svc-daemon neutron-server neutron neutron-server \
    "--config-file /etc/neutron/neutron.conf  --config-file /etc/neutron/plugins/openvswitch/ovs_neutron_plugin.ini --config-dir /etc/neutron"
