#!/bin/bash
set -eux

os-svc-install -n keystone -u keystone -r https://github.com/openstack/keystone.git
os-svc-daemon keystone keystone keystone-all "--config-dir /etc/keystone --log-config /etc/keystone/logging.conf"
install -m 0755 -o keystone -g keystone -d /etc/keystone/ssl

install-packages percona-toolkit
install -m 0755 -o root -g root $(dirname $0)/../cleanup-keystone-tokens.sh /usr/local/bin
install -m 0640 -o root -g root $(dirname $0)/../keystone.crontab /etc/cron.d/keystone
