#!/bin/bash
set -eux

DISTRO=`lsb_release -si` || true

os-svc-install -n keystone -u keystone -r /opt/stack/keystone
os-svc-daemon keystone keystone keystone-all "--config-dir /etc/keystone --log-config /etc/keystone/logging.conf"
install -m 0755 -o keystone -g keystone -d /etc/keystone/ssl

# percona-tookit is NOT supported on Fedora (retrieved 25-06-2013)
# http://www.percona.com/mysql-support/policies/percona-toolkit-supported-platforms-and-versions
if [[ "Ubuntu RedHatEnterpriseServer CentOS" =~ "$DISTRO" ]]; then
    install-packages percona-toolkit
    install -m 0755 -o root -g root $(dirname $0)/../cleanup-keystone-tokens.sh /usr/local/bin
    install -m 0640 -o root -g root $(dirname $0)/../keystone.crontab /etc/cron.d/keystone
fi
