#!/bin/bash
set -eux

os-svc-install -n keystone -u keystone -r https://github.com/openstack/keystone.git
os-svc-daemon keystone keystone keystone-all "--config-dir /etc/keystone --log-config /etc/keystone/logging.conf"
install -m 0755 -o keystone -g keystone -d /etc/keystone/ssl
