#!/bin/bash
#
# Copyright 2013 Hewlett-Packard Development Company, L.P.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eux
set -o pipefail

if [ ! -e "/var/lib/use-ephemeral/stateful-paths" ]; then
    exit 0
fi

while read -r; do
    state_path="/mnt/state$REPLY"
    state_dir=$(dirname "$state_path")
    reference_path="/var/lib/use-ephemeral$REPLY"
    mkdir -p "$state_dir"
    if [ -e "$reference_path" -a ! -L "$state_path" -a ! -e "$state_path" ]; then
        if [ -d "$reference_path" ] ; then
            reference_path="${reference_path}/"
        fi
        rsync -av "${reference_path}" "$state_path"
    fi
done < "/var/lib/use-ephemeral/stateful-paths"
