#!/bin/bash
# Copyright 2014 Hewlett-Packard Development Company, L.P.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

set -eux
set -o pipefail

CA_CERT=/etc/ssl/from-heat-ca.crt
CA_CERT_SIZE=$(stat -c '%s' "$CA_CERT")
DISTRO=`lsb_release -si` || true

# A PEM encoded SSL Cert will have at least 54 characters for the START/END
# markers.
if [ $CA_CERT_SIZE -gt 54 ]; then
  if [[ "Ubuntu Debian" =~ "${DISTRO}" ]]; then
    # On Debian, place the CA certificate where 'update-ca-certificates' will find it
    cp ${CA_CERT} /usr/local/share/ca-certificates/from-heat-ca.crt
    update-ca-certificates
  else
    # On RPM-based distros, place the CA certificate where 'update-ca-trust' will find it
    cp ${CA_CERT} /etc/pki/ca-trust/source/anchors/from-heat-ca.crt
    update-ca-trust
  fi
fi
