#!/bin/bash

set -eux

os-svc-daemon swift-account swift swift-account-server /etc/swift/account-server.conf
os-svc-daemon swift-container swift swift-container-server /etc/swift/container-server.conf
os-svc-daemon swift-object swift swift-object-server /etc/swift/object-server.conf
