#!/bin/bash

set -eux

os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-account swift swift-account-server /etc/swift/account-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-account-auditor swift swift-account-auditor /etc/swift/account-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-account-reaper swift swift-account-reaper /etc/swift/account-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-account-replicator swift swift-account-replicator /etc/swift/account-server.conf

os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-container swift swift-container-server /etc/swift/container-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-container-auditor swift swift-container-auditor /etc/swift/container-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-container-replicator swift swift-container-replicator /etc/swift/container-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-container-sync swift swift-container-sync /etc/swift/container-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-container-updater swift swift-container-updater /etc/swift/container-server.conf

os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-object swift swift-object-server /etc/swift/object-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-object-auditor swift swift-object-auditor /etc/swift/object-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-object-replicator swift swift-object-replicator /etc/swift/object-server.conf
os-svc-daemon -l -i "$SWIFT_VENV_DIR" swift-object-updater swift swift-object-updater /etc/swift/object-server.conf

ln -s $SWIFT_VENV_DIR/bin/swift-recon-cron /usr/local/bin/swift-recon-cron
