#!/bin/sh

# Install controller base requiered packages

set -e
set -o xtrace

install -D -m 0644 -o root -g root  $(dirname $0)/my.cnf /etc/mysql/my.cnf
if [ "$(dib-init-system)" = "upstart" ] ; then
    install $(dirname $0)/mysql-set-server-id.upstart /etc/init/mysql-set-server-id.conf
else
    echo WARNING: server-id will not be set on systems that boot this image!
fi

install-packages sysstat mytop percona-toolkit mysql-server-5.5 mysql-client-5.5 python-mysqldb
