#!/bin/bash
set -eux

PUBLIC_INTERFACE=$(os-config-applier --key quantum.ovs.public_interface --key-default '')

ovs-vsctl --no-wait -- --may-exist add-br br-ex
ovs-vsctl --no-wait br-set-external-id br-ex bridge-id br-ex

if [ -n "$PUBLIC_INTERFACE" ] ; then
    ovs-vsctl --no-wait -- --may-exist add-port br-ex $PUBLIC_INTERFACE
fi

service quantum-metadata-agent restart
service quantum-l3-agent restart
service quantum-dhcp-agent restart
