#!/bin/bash
set -eu

# mariadb clients (from mariadb.org) expect the socket at
# /var/lib/mysql/mysql.sock
#
# mysql server is started from 51-init-openstack (reset-db script) - we need to
# create symlink to make sure reset-db will not fail
[ -d /var/lib/mysql ] || install -d -m 0755 -o mysql -g mysql /var/lib/mysql
[ -d /var/run/mysqld ] || ln -sf /var/run/mariadb/ /var/run/mysqld
ln -sf /var/run/mysqld/mysqld.sock /var/lib/mysql/mysql.sock
