#!/bin/bash
set -eux

install-packages python-pip python-virtualenv

virtualenv --setuptools /opt/stack/venvs/os-apply-config

/opt/stack/venvs/os-apply-config/bin/pip install -U os-apply-config

ln -s /opt/stack/venvs/os-apply-config/bin/os-apply-config /usr/local/bin/os-apply-config
ln -s /opt/stack/venvs/os-apply-config/bin/os-config-applier /usr/local/bin/os-config-applier

TEMPLATE_ROOT=$(os-apply-config --print-templates)
mkdir -p $TEMPLATE_ROOT
