#!/bin/bash
# Note that this relies on the detail that all elements share one dir
# inside the chroot. This will copy all the files that elements have
# added to element/os-config-applier or element/os-apply-config into the
# appropriate location.
set -eux
TEMPLATE_ROOT=$(os-apply-config --print-templates)
TEMPLATE_SOURCE=$(dirname $0)/../os-config-applier
rsync -r $TEMPLATE_SOURCE/ $TEMPLATE_ROOT/
TEMPLATE_SOURCE=$(dirname $0)/../os-apply-config
rsync -r $TEMPLATE_SOURCE/ $TEMPLATE_ROOT/
