#!/bin/bash
set -eu

DISTRO=`lsb_release -si` || true
if [ "openSUSE project" = "$DISTRO" ]; then
    if [ -e /var/run/mysqld/mysqld.sock ]; then
        if [ ! -d /var/run/mysql ]; then
            mkdir /var/run/mysql
        fi
        ln -sf /var/run/mysqld/mysqld.sock /var/run/mysql/mysql.sock
    fi
fi
