#!/bin/bash
set -eux

# For nova-rpc-zmq-receiver
mkdir -p /var/run/openstack
# XXX Hrm, but what if others use this dir?
chown -R nova:nova /var/run/openstack

mkdir -p /var/run/nova
chown -R nova:nova /var/run/nova

nova-manage db sync

os-svc-enable -n nova-conductor
os-svc-enable -n nova-api
os-svc-enable -n nova-cert
os-svc-enable -n nova-scheduler
os-svc-enable -n nova-consoleauth

os-svc-restart -n nova-conductor
os-svc-restart -n nova-api
os-svc-restart -n nova-cert
os-svc-restart -n nova-scheduler
os-svc-restart -n nova-consoleauth
