#!/bin/bash
set -eux
set -o pipefail

os-svc-install $KEYSTONE_EXTRA_INSTALL_OPTS -i "$KEYSTONE_VENV_DIR" -u keystone -r /opt/stack/keystone

# Workaround for https://bugs.launchpad.net/tripleo/+bug/1288425
$KEYSTONE_VENV_DIR/bin/pip install -U kombu
$KEYSTONE_VENV_DIR/bin/pip install -U qpid-python
