#!/bin/bash
set -eux
set -o pipefail

RELEASE=`lsb_release -r` || true

os-svc-install $KEYSTONE_EXTRA_INSTALL_OPTS -i "$KEYSTONE_VENV_DIR" -u keystone -r /opt/stack/keystone
os-svc-daemon -a -i "$KEYSTONE_VENV_DIR" keystone keystone keystone-all "--config-dir /etc/keystone"
install -m 0755 -o keystone -g keystone -d /etc/keystone/ssl

ln -s $KEYSTONE_VENV_DIR/bin/keystone-manage /usr/local/bin/keystone-manage

cp /opt/stack/keystone/etc/policy.json /etc/keystone/policy.json
cp /opt/stack/keystone/etc/keystone-paste.ini /etc/keystone/keystone-paste.ini

# Reserve the Keystone port out of the ephemeral port range.
sysctl-append-value net.ipv4.ip_local_reserved_ports 35357

# Install scripts to clean up tokens
install -m 0755 -o root -g root $(dirname $0)/../cleanup-keystone-tokens.sh /usr/local/bin
install -m 0640 -o root -g root $(dirname $0)/../keystone.crontab /etc/cron.d/keystone

# LDAP backend support
install-packages -m keystone ldap_devel_package sasl_devel_package ssl_devel_package
$KEYSTONE_VENV_DIR/bin/pip install -U python-ldap ldappool

# percona-tookit is NOT supported on Fedora (retrieved 25-06-2013)
# http://www.percona.com/mysql-support/policies/percona-toolkit-supported-platforms-and-versions
if [[ "ubuntu rhel rhel7 centos7" =~ "$DISTRO_NAME" ]]; then
    if [[ "$DISTRO_NAME" =~ "rhel" && "$RELEASE" =~ "7." ]]; then
        exit 0
    fi
    install-packages percona-toolkit
fi

add-selinux-path-substitution /usr/bin $KEYSTONE_VENV_DIR/bin
