#!/bin/bash
set -eu

[ -d /mnt/state/var/lib/glance ] || install -d -D -m 0770 -o glance -g glance /mnt/state/var/lib/glance
[ -d /mnt/state/var/lib/glance/images ] || install -d -D -m 0770 -o glance -g glance /mnt/state/var/lib/glance/images
[ -d /mnt/state/var/log/glance ] || install -d -D -m 0755 -o glance -g glance /mnt/state/var/log/glance

/opt/stack/venvs/glance/bin/glance-manage db_sync

os-svc-enable -n glance-api
os-svc-enable -n glance-reg

service glance-api restart
service glance-reg restart
