#!/bin/bash
set -eux

os-svc-daemon -i "$NEUTRON_VENV_DIR" -n neutron-l3-agent -u neutron -c neutron-l3-agent -- --config-file /etc/neutron/l3_agent.ini --config-dir /etc/neutron
os-svc-daemon -i "$NEUTRON_VENV_DIR" -n neutron-metadata-agent -u neutron -c neutron-metadata-agent -- --config-file /etc/neutron/metadata_agent.ini --config-dir /etc/neutron

# This has to be on the path of the agent that runs it http://pad.lv/1182704
ln -sf $NEUTRON_VENV_DIR/bin/neutron-ns-metadata-proxy /usr/bin
