#!/bin/bash
set -eux
set -o pipefail

install-packages iptables


if [[ "ubuntu debian" =~ "$DISTRO_NAME" ]]; then
    # Note in later versions will
    # need netfilter-persistent package
    install-packages iptables-persistent
fi
