#!/bin/bash
set -eux
set -o pipefail

install-packages iptables

DISTRO=`lsb_release -si` || true

if [[ "Debian Ubuntu" =~ $DISTRO ]]; then
    # Note in later versions will
    # need netfilter-persistent package
    install-packages iptables-persistent
fi
