#!/bin/bash
set -eux
set -o pipefail

if [[ "rhel rhel7 centos7 fedora" =~ "$DISTRO_NAME" ]]; then
    echo '# empty ruleset created by tripleo-image-elements' > /etc/sysconfig/iptables
    echo '# empty ruleset created by tripleo-image-elements' > /etc/sysconfig/ip6tables

fi
