#!/bin/bash
set -eux

DISTRO=`lsb_release -si` || true

install-packages openvswitch-switch openvswitch-datapath-dkms

# for BUG: https://bugs.launchpad.net/neutron/+bug/1225232
echo "qpid-python" | tee -a /opt/stack/neutron/requirements.txt

os-svc-install -n neutron -u neutron -r /opt/stack/neutron

mkdir -p /var/lib/neutron && chown -R neutron:neutron /var/lib/neutron

ln -sf /opt/stack/venvs/neutron/bin/neutron-rootwrap /usr/bin/neutron-rootwrap
ln -sf /opt/stack/venvs/neutron/etc/neutron/rootwrap.d /etc/neutron/rootwrap.d

cp /opt/stack/neutron/etc/api-paste.ini /etc/neutron/api-paste.ini
cp /opt/stack/neutron/etc/policy.json /etc/neutron/policy.json

echo "neutron ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/neutron
echo "Defaults:neutron !requiretty" >> /etc/sudoers.d/neutron
chmod 0440 /etc/sudoers.d/neutron
visudo -c

if [ "$DIB_INIT_SYSTEM" == "systemd" ]; then
    systemctl enable openvswitch.service
fi
