#!/bin/bash
set -eux

# Due to trunk neutron relying on trunk neutronclient, we need
# trunk neutronclient - https://bugs.launchpad.net/neutron/+bug/1280941
/opt/stack/venvs/neutron/bin/pip install -U git+https://git.openstack.org/openstack/python-neutronclient

