#!/bin/bash

set -eu

sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-openstackclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-ceilometerclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-cinderclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-glanceclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-heatclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-ironicclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-neutronclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-novaclient"
sudo rm -fr "${TMP_MOUNT_PATH}/opt/stack/python-swiftclient"
