#!/bin/bash
#
# Compiles and installs the policies under /opt/stack/selinux-policy.
#
set -eux
set -o pipefail

if [ -x /usr/sbin/semanage ]; then
    cd /tmp
    for file in $(ls /opt/stack/selinux-policy/*.te); do
        filename=$(basename $file)
        filename_no_ext=${filename%.*}
        # compile policy
        cp $file /tmp
        make -f /usr/share/selinux/devel/Makefile $filename_no_ext.pp
        # install policy
        semodule -i /tmp/$filename_no_ext.pp
        rm /tmp/$filename_no_ext.*
    done
fi
