#!/bin/bash
set -eux

ln -s $CINDER_VENV_DIR/bin/cinder-manage /usr/local/bin/cinder-manage

os-svc-daemon cinder-api cinder cinder-api "--config-dir /etc/cinder"
os-svc-daemon cinder-scheduler cinder cinder-scheduler "--config-dir /etc/cinder"
