#!/bin/bash

set -eux

install-packages \
    python-cinderclient \
    python-glanceclient \
    python-heatclient \
    python-ironicclient \
    python-keystoneclient \
    python-neutronclient \
    python-novaclient \
    python-swiftclient
