#!/bin/bash
set -eux

mkdir -p /mnt/state/var/lib/nova/instances/_base
chown nova:kvm /mnt/state/var/lib/nova/instances
chown nova:kvm /mnt/state/var/lib/nova/instances/_base
chmod 750 /mnt/state/var/lib/nova/instances
chmod 750 /mnt/state/var/lib/nova/instances/_base
