#!/bin/bash
# We need to install this early in install.d because other elements will
# need to use os-refresh-config --print-base to know where to put files

set -eux

# pip and virtualenv is installed by the pip-and-virtualenv element

virtualenv --setuptools /opt/stack/venvs/os-refresh-config

# Need setuptools>=1.0 to manage connections when
# downloading from pypi using http_proxy and https_proxy
/opt/stack/venvs/os-refresh-config/bin/pip install -U pip
/opt/stack/venvs/os-refresh-config/bin/pip install -U 'setuptools>=1.0'
/opt/stack/venvs/os-refresh-config/bin/pip install -U os-refresh-config

ln -s /opt/stack/venvs/os-refresh-config/bin/os-refresh-config /usr/local/bin/os-refresh-config

for d in pre-configure.d configure.d migration.d post-configure.d; do
  install -m 0755 -o root -g root -d /opt/stack/os-config-refresh/$d
done
