#!/bin/bash

# install check-mk-agent and the logwatch plugin

set -eux
set -o pipefail

# check_mk is disabled by default so we need to enable it here
sed -i "s/\tdisable        = yes/\tdisable        = no/g" /etc/xinetd.d/check_mk

os-svc-enable -an xinetd
