#!/bin/bash

# install check-mk-agent and the logwatch plugin

set -eux
set -o pipefail

install-packages xinetd check-mk-agent check-mk-agent-logwatch
# check_mk is disabled by default so we need to enable it here
sed -i "s/\tdisable        = yes/\tdisable        = no/g" /etc/xinetd.d/check_mk

os-svc-enable -n xinetd
