#!/bin/bash
set -eu

[ -x /usr/sbin/semanage ] || exit 0

semanage fcontext -a -t rabbitmq_var_lib_t "/var/lib/rabbitmq(/.*)?"
restorecon -Rv /var/lib/rabbitmq

semanage fcontext -a -t rabbitmq_var_log_t "/var/log/rabbitmq(/.*)?"
restorecon -Rv /var/log/rabbitmq
