#!/bin/bash
set -eux

install-packages git build-essential python-dev
install-packages tgt busybox # to run diskimage-builder for deploy ramdisk

install -m 0755 -o root -g root -d /opt/stack/boot-stack

echo 'nameserver 8.8.8.8' > /etc/resolvconf/resolv.conf.d/head

# fake heat metadata
mkdir -p /var/lib/cloud/data
install -m 0755 -o root -g root $(dirname $0)/../config.json /var/lib/cloud/data/cfn-init-data

# tools
for f in `ls $(dirname $0)/../bin`; do
  install -m 0755 -o root -g root $(dirname $0)/../bin/$f /usr/local/bin/$f
done

# openstack creds
# TODO: generate random creds.
install -m 0755 -o root -g root $(dirname $0)/../stackrc /root/stackrc
echo "source /root/stackrc" >> /root/.bash_profile

# client tools
for client in nova quantum glance; do
  repo=python-${client}client
  venvs=/opt/stack/venvs
  git clone --depth 1 https://github.com/openstack/$repo.git /opt/stack/$repo

  # required for a cliff version conflict. this can be removed once cliff will accept prettytable >0.7
  pip install cliff

  pushd /opt/stack/$repo
  [ -e tools/pip-requires ] && pip install -r tools/pip-requires
  python setup.py develop --script-dir /usr/local/bin
  popd

done

# image toolchain
git clone https://github.com/stackforge/diskimage-builder.git /opt/stack/diskimage-builder

# rabbit
install-packages rabbitmq-server
# rabbit's default init.d script is broken.
update-rc.d -f rabbitmq-server remove
rm /etc/init.d/rabbitmq-server
cat > /etc/init/rabbitmq-server.conf <<eof
start on runlevel [2345]
stop on runlevel [016]
respawn

exec /usr/sbin/rabbitmq-server > /var/log/rabbitmq/startup_log \
                              2> /var/log/rabbitmq/startup_err
post-start exec /usr/sbin/rabbitmqctl wait >/dev/null 2>&1
eof

# db
install-packages mysql-server python-mysqldb
sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/my.cnf

function deps {
  apt-get update
  install-packages screen ccze
  install-packages git ipmitool python-dev python-pip python-greenlet python-mysqldb libxml2-dev libxslt-dev python-zmq
  install-packages openvswitch-common openvswitch-controller openvswitch-switch open-iscsi
  install-packages python-numpy python-lxml
}

function ip_forwarding {
  cat > /etc/sysctl.conf <<eof
net.ipv4.ip_forward=1
eof
}

deps
ip_forwarding
