#!/bin/bash
# We need to install this early in install.d because other elements will
# need to use os-refresh-config --print-base to know where to put files

set -eux

install-packages python-virtualenv

virtualenv --setuptools /opt/stack/venvs/os-refresh-config

/opt/stack/venvs/os-refresh-config/bin/pip install -U os-refresh-config

ln -s /opt/stack/venvs/os-refresh-config/bin/os-refresh-config /usr/local/bin/os-refresh-config

for d in pre-configure.d configure.d migration.d post-configure.d; do
  install -m 0755 -o root -g root -d /opt/stack/os-config-refresh/$d
done
