#!/bin/bash
install -m 0755 -o root -g root $(dirname $0)/cfn-hup-wrapper /usr/local/bin/cfn-hup-wrapper
cat > /etc/cron.d/cfn-hup <<EOF
# This is a workaround for cfn-hup not actually being a daemon
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

*/5 * * * * root cfn-hup-wrapper
EOF
