#!/bin/bash
# This cannot be an os-apply-config template as this is what runs
# os-apply-config for the first time.
cat > /etc/cron.d/cfn-hup <<EOF
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

# Ensure cfn-hup has a configuration
@reboot root os-refresh-config 2>&1 | logger -t os-refresh-config
# This is a workaround for cfn-hup not actually being a daemon
*/5 * * * * root cfn-hup --no-daemon
EOF
