#!/usr/bin/env python
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.

import fcntl
import os
import random
import subprocess
import sys
import time

if len(sys.argv) > 1:
    max_sleep = int(sys.argv[1])
else:
    max_sleep = 59

randskew = random.randint(0, max_sleep)
time.sleep(randskew)
with open('/run/os-refresh-config-cfn-hup.lock', 'a') as lock:
    fcntl.flock(lock, fcntl.LOCK_EX)
    lock.seek(0)
    lock.truncate()
    lock.write('Lock held by process id %s\n' % os.getpid())
    lock.flush()
    try:
        subprocess.check_call(['cfn-hup', '--no-daemon'])
    except subprocess.CalledProcessError as e:
        sys.stderr.write("%s\n", e)
        sys.exit(e.returncode)
