#!/bin/bash
set -eu

OK=/opt/stack/gearman-iptables.ok

if [ -e $OK ] ; then
    exit 0
fi

DISTRO=`lsb_release -si` || true

if [[ "Fedora" = "$DISTRO" ]]; then

    # Check if the iptables service is active
    if systemctl is-active iptables.service ; then
        IPT_FILE=/etc/sysconfig/iptables
        if [ -f $IPT_FILE ]; then
            iptables-restore < $IPT_FILE
        fi

        # Gearman server
        iptables -I INPUT -p tcp --dport 4730 -j ACCEPT

        iptables-save > $IPT_FILE

    fi

fi

touch $OK
