#!/bin/bash
set -ue
set -o pipefail

os-svc-enable -an heat-api
os-svc-enable -an heat-api-cfn
os-svc-enable -an heat-api-cloudwatch

os-svc-restart -an heat-api
os-svc-restart -an heat-api-cfn
os-svc-restart -an heat-api-cloudwatch
