#!/bin/bash

os-svc-enable -n heat-api
os-svc-enable -n heat-api-cfn
os-svc-enable -n heat-api-cloudwatch

os-svc-restart -n heat-api
os-svc-restart -n heat-api-cfn
os-svc-restart -n heat-api-cloudwatch
