#!/bin/bash
set -eux

manifest=$(get-pip-manifest os-apply-config)

virtualenv --setuptools /opt/stack/venvs/os-apply-config
set +u
source /opt/stack/venvs/os-apply-config/bin/activate
set -u

if [ -n "$manifest" ]; then
    use-pip-manifest $manifest
else
    # bug #1201253 : virtualenv-1.10.1 embeds setuptools-0.9.8, which
    # doesn't manage correctly HTTPS sockets when downloading pbr from
    # https://pypi.python.org/simple/ if using http_proxy and https_proxy
    # envvars
    /opt/stack/venvs/os-apply-config/bin/pip install -U 'setuptools>=1.0'
    # bug #1293812 : Avoid easy_install triggering on pbr.
    /opt/stack/venvs/os-apply-config/bin/pip install -U 'pbr>=0.6,<1.0'
    /opt/stack/venvs/os-apply-config/bin/pip install --pre -U os-apply-config
fi

# Write the manifest of what was installed
write-pip-manifest os-apply-config

ln -s /opt/stack/venvs/os-apply-config/bin/os-apply-config /usr/local/bin/os-apply-config
ln -s /opt/stack/venvs/os-apply-config/bin/os-config-applier /usr/local/bin/os-config-applier

set +u
deactivate
set -u
