#!/bin/bash
set -eux

# If NEUTRON_VENV_DIR is set, then need to fix up the l3.filters rootwrap file to allow l3-agent to
# kill metadata-proxy processes when routers are deleted.
if [ -n "${NEUTRON_VENV_DIR}" ]
then
    sed -i "s, python, ${NEUTRON_VENV_DIR}/bin/python," /etc/neutron/rootwrap.d/l3.filters
fi

os-svc-daemon -i "$NEUTRON_VENV_DIR" -n neutron-l3-agent -u neutron -c neutron-l3-agent -- --config-file /etc/neutron/l3_agent.ini --config-dir /etc/neutron
os-svc-daemon -i "$NEUTRON_VENV_DIR" -n neutron-metadata-agent -u neutron -c neutron-metadata-agent -- --config-file /etc/neutron/metadata_agent.ini --config-dir /etc/neutron

# This has to be on the path of the agent that runs it http://pad.lv/1182704
ln -sf $NEUTRON_VENV_DIR/bin/neutron-ns-metadata-proxy /usr/bin
