#!/bin/bash
set -eux

# syslinux is installed by nova-compute, which contains pxelinux.0
install-packages tftpd-hpa xinetd

mkdir -p /tftpboot/pxelinux.cfg/
if [ -f /usr/lib/syslinux/pxelinux.0 ]; then
  cp /usr/lib/syslinux/pxelinux.0 /tftpboot/ # Ubuntu
elif [ -f /usr/share/syslinux/pxelinux.0 ]; then
  cp /usr/share/syslinux/pxelinux.0 /tftpboot/ # Fedora/RHEL
else
  echo "Failed to find pxelinux.0."
  exit 1
fi

# Disable the tftp-hpa upstart job, we're using xinetd
[ -f /etc/init/tftpd-hpa.conf ] && echo "manual" > /etc/init/tftpd-hpa.override

cat > /etc/xinetd.d/tftp << EOF
service tftp
{
  protocol        = udp
  port            = 69
  socket_type     = dgram
  wait            = yes
  user            = root
  server          = /usr/sbin/in.tftpd
  server_args     = --map-file /tftpboot/map-file /tftpboot
  disable         = no
}
EOF

# Adds support for tftp requests that don't include the directory name.
echo 'r ^([^/]) /tftpboot/\1' > /tftpboot/map-file
