#!/bin/bash

set -eux

if [[ "rhel rhel7 centos7 fedora" =~ "$DISTRO_NAME" ]]; then
    ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini

    # Packaged neutron is providing a requires.txt which breaks dependencies at
    # runtime. See:
    # https://bugzilla.redhat.com/show_bug.cgi?id=1057615
    rm -f /usr/lib/python2.7/site-packages/neutron-*.egg-info/requires.txt
fi
os-svc-daemon -i "$NEUTRON_VENV_DIR" -n neutron-server -u neutron
