#!/bin/bash

set -eux

install-openstack-client $CEILOMETERCLIENT_EXTRA_INSTALL_OPTS -c ceilometer -i $CEILOMETERCLIENT_VENV_DIR

add-selinux-path-substitution /usr/bin $CEILOMETERCLIENT_VENV_DIR/bin
